<?php

/**
 * SPDX-FileCopyrightText: 2015-2020 Klarna Bank AB (publ)
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: Apache-2.0
 * @package Klarna_Payments
 */
?>
<script type="text/javascript" id="klarna-credit-lib-x">
    /* <![CDATA[ */
    (function(w,d) {
        var url = 'https://x.klarnacdn.net/kp/lib/v1/api.js';
        n = d.createElement('script');
        c = d.getElementById('klarna-credit-lib-x');
        n.async = !0;
        n.src = url + '?' + (new Date()).getTime();
        c.parentNode.replaceChild(n, c);
    })(this,document);

    function fireWhenReady(method) {
        if (window.hasOwnProperty('Klarna')) {
            method();
        } else {
            setTimeout(function () {
                fireWhenReady(method);
            }, 100);
        }
    }

    // Used to register Klarna payment methods that need to call authorize on payment.save()
    var klarnaPaymentArray = [];
    /* ]]> */
</script>
