<?php

/**
 * SPDX-FileCopyrightText: 2015-2020 Klarna Bank AB (publ)
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: Apache-2.0
 * @package Klarna_Payments
 */

/**
 * @var Klarna_Payments_Block_Payments $this
 */
?>
<?php if (Mage::getStoreConfigFlag('payment/' . $this->getMethodCode() . '/active')): ?>
    <?php $payment = Mage::getSingleton('checkout/session')->getquote()->getPayment(); ?>
    <?php $subType = Mage::getSingleton('checkout/session')->getKlarnaPaymentsSelected(); ?>
    <script type="text/javascript">
        function Klarna<?php echo $this->getFunctionName(); ?>Init() {
            fireWhenReady(function () {
                Klarna.<?php echo $this->getFunctionName(); ?>.init({
                    client_token: "<?php echo $this->getClientToken(); ?>"
                });
            })
        }

        document.observe("dom:loaded", function () {
            Klarna<?php echo $this->getFunctionName(); ?>Init();
            <?php if ($payment->getMethod() && $payment->getMethodInstance() instanceof Klarna_Core_Model_Payment_Method_Abstract): ?>
                jQuery('#p_method_klarna_payments_<?php echo $subType; ?>').click();
            <?php endif; ?>
        });
    </script>
<?php endif; ?>
<?php echo $this->getChildHtml('', false);
