<?php

/**
 * SPDX-FileCopyrightText: 2015-2020 Klarna Bank AB (publ)
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: Apache-2.0
 * @package Klarna_Payments
 */

/**
 * @var Klarna_Payments_Block_Payments $this
 */
?>
<?php if (Mage::getStoreConfigFlag('payment/' . $this->getMethodCode() . '/active')) : ?>
<script type="text/javascript">
//<![CDATA[
    var usregions = <?php echo $this->getRegionsUS(); ?>;
//]]>
</script>
<?php endif; ?>