<?php

/**
 * SPDX-FileCopyrightText: 2015-2020 Klarna Bank AB (publ)
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: Apache-2.0
 * @package Klarna_Payments
 */

/**
 * Klarna payment type template
 */

/** @var Klarna_Payments_Block_Info_Payments $this */
?>
<p><img width="150" src="https://cdn.klarna.com/1.0/shared/image/generic/logo/<?php echo Mage::helper('klarna_payments')->getLocale($this->getInfo()->getOrder()->getStore()); ?>/basic/logo_black.png?width=300"
        alt="<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>"/></p>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
    <table>
        <?php foreach ($_specificInfo as $_label => $_value): ?>
            <tr>
                <td><?php echo $this->escapeHtml($_label) ?>:</td>
                <td>
                    <?php if ($this->isStringUrl($_value)): ?>
                        <a href="<?= $_value; ?>" target="_blank"><?= $this->__('Click Here') ?></a>
                    <?php else: ?>
                        <?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true))) ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?php echo $this->getChildHtml() ?>
