<?php

/**
 * SPDX-FileCopyrightText: 2015-2020 Klarna Bank AB (publ)
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: Apache-2.0
 * @package Klarna_Payments
 */

/**
 * Klarna payment type template
 */

/** @var $this Klarna_Payments_Block_Info_Payments */
?>
<p><img width="150" src="https://cdn.klarna.com/1.0/shared/image/generic/logo/<?php echo Mage::helper('klarna_payments')->getLocale(); ?>/basic/logo_black.png?width=300"
        alt="<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>"/></p>
<br />
<p><img width="100" src="<?php echo $this->getLogo() ?>?width=300"
        alt="<?php echo $this->getName() ?>"/>
    <?php echo $this->getName() ?>
</p>

<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
    <table>
        <tbody>
        <?php foreach ($_specificInfo as $_label => $_value): ?>
            <tr>
                <th><strong><?php echo $this->escapeHtml($_label) ?>:</strong></th>
            </tr>
            <tr>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n")) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php echo $this->getChildHtml() ?>
